version: '3.8'

services:
  reindustrialization-report:
    image: ${DOCKER_REGISTRY:-localhost}/reindustrialization-report:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PERPLEXITY_API_KEY=${PERPLEXITY_API_KEY}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - SMTP_SERVER=${SMTP_SERVER}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SENDER_EMAIL=${SENDER_EMAIL}
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints:
          - node.role == worker
    networks:
      - reindustrialization-net

networks:
  reindustrialization-net:
    driver: overlay
